version: 2.1

jobs:
  build-docker-image:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo

    steps:
      - checkout

      # Enable Docker engine
      - setup_remote_docker

      # Login to Docker Hub using environment variables
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Build Docker image from your Dockerfile
      - run:
          name: Build Docker Image
          command: |
            docker build -t marianreda/spring-petclinic:${CIRCLE_SHA1} .

      # Push image to Docker Hub
      - run:
          name: Push Docker Image
          command: |
            docker push marianreda/spring-petclinic:${CIRCLE_SHA1}

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build-docker-image

