version: 2.1

orbs:
  docker: circleci/docker@2.1.2
jobs:
  build-docker-image:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo

    steps:
      - checkout

      # Enable Docker engine
      - setup_remote_docker

      # Login to Docker Hub
      - docker/login:
          username: DOCKERHUB_USERNAME      # no $ here
          password: DOCKERHUB_PASSWORD

      # Build Docker image (use image + tag separately)
      - docker/build:
          image: marianreda/spring-petclinic
          tag: ${CIRCLE_SHA1}

      # Push the image to Docker Hub
      - docker/push:
          image: marianreda/spring-petclinic
          tag: ${CIRCLE_SHA1}

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build-docker-image
