version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-and-dockerize:
    docker:
      - image: cimg/openjdk:25.0  # build with Java 25
    steps:
      - checkout

      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      - run:
          name: Build JAR
          command: ./mvnw clean package -DskipTests

      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/spring-petclinic:latest .

      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_USERNAME/spring-petclinic:latest

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-dockerize
