version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-docker-image:
    docker:
      - image: cimg/base:stable                 #debian ubuntu, Docker CLI support
    working_directory: ~/repo
    
    steps:
      - checkout
      - docker/login:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - docker/build:
          image: marianreda/spring-petclinic:${CIRCLE_SHA1}   #commit id 
      - docker/push:
          image: marianreda/spring-petclinic:${CIRCLE_SHA1}
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-docker-image

